function px4_send_rate_setpoint(client, thrust, roll_rate, pitch_rate, yaw_rate, config)
% PX4_SEND_RATE_SETPOINT Send body rates setpoint (body rates + thrust) to drone
%   Sends desired body rates and thrust command to the drone

    command = struct('type', 'set_body_rates', ...
                     'thrust', thrust, ...
                     'roll_rate', roll_rate, ...
                     'pitch_rate', pitch_rate, ...
                     'yaw_rate', yaw_rate);
    px4_send_json_command(client, command, config);
    
end